services:
   nginx:
     build: ./nginx/
     ports:
       - 8082:80
  
     volumes:
       - ./src/:/var/www/html/

   php:
     build: ./src/
     expose:
       - 9000
     volumes:
       - ./src/:/var/www/html/

   memcached:
     container_name: testMemcached
     image: memcached:latest
     ports:
       - "11211:11211"